# Generated by Django 4.0.5 on 2022-07-17 15:45

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.CharField(max_length=100, verbose_name='Volume m3')),
                ('axles', models.CharField(max_length=100, verbose_name='Number of axles')),
            ],
            options={
                'ordering': ['axles', 'volume'],
            },
        ),
        migrations.CreateModel(
            name='TrailerInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Dispatchers ID for the Trailer', primary_key=True, serialize=False)),
                ('dexpected_return', models.DateField(blank=True, null=True, verbose_name='Will be available')),
                ('status', models.CharField(blank=True, choices=[('ser', 'Service'), ('tri', 'Trip'), ('rea', 'Ready'), ('res', 'Reserved')], default='res', help_text='Statusas', max_length=3)),
            ],
            options={
                'ordering': ['dexpected_return'],
            },
        ),
        migrations.RemoveField(
            model_name='truckinstance',
            name='truck',
        ),
        migrations.AlterModelOptions(
            name='producer',
            options={},
        ),
        migrations.RemoveField(
            model_name='producer',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='producer',
            name='country',
        ),
        migrations.RemoveField(
            model_name='trailer',
            name='name',
        ),
        migrations.AddField(
            model_name='producer',
            name='name',
            field=models.CharField(blank=True, help_text='Enter the Name of the Producer (e.g. Lamberet)', max_length=200, null=True, verbose_name='Brand'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='platenr',
            field=models.CharField(blank=True, help_text='Plate number', max_length=6, null=True, verbose_name='Plate number'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='producer',
            field=models.ManyToManyField(help_text='Enter the Name of the producer', to='dispatcher.producer'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='summary',
            field=models.TextField(blank=True, help_text='Other information', max_length=1000, null=True, verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Type'),
        ),
        migrations.DeleteModel(
            name='Truck',
        ),
        migrations.DeleteModel(
            name='TruckInstance',
        ),
        migrations.AddField(
            model_name='trailerinstance',
            name='trailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatcher.trailer'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='features',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dispatcher.features'),
        ),
    ]
