# Generated by Django 4.0.5 on 2022-07-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher', '0002_features_trailerinstance_remove_truckinstance_truck_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producer',
            options={'verbose_name': 'Producer', 'verbose_name_plural': 'Producers'},
        ),
    ]
