# Generated by Django 4.0.5 on 2022-07-28 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dispatcher', '0003_alter_producer_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailerinstance',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='features',
            name='axles',
            field=models.CharField(max_length=1, verbose_name='Number of axles'),
        ),
        migrations.AlterField(
            model_name='features',
            name='volume',
            field=models.CharField(max_length=2, verbose_name='Volume m3'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='features',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailers', to='dispatcher.features'),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='platenr',
            field=models.CharField(blank=True, help_text='Plate number', max_length=5, null=True, verbose_name='Plate number'),
        ),
    ]
